id: P010332
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN7747
  title: བོད་ཀྱི་དག་ཡིག
  author: ''
  volumes:
    2193e4bd58204b6d89c856e0907c1268:
      image_group_id: I3CN8712
      title: ''
      volume_number: 1
      total_pages: 292
      base_file: v001.txt
