id: I939E4318
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:59:34+00:00'
last_modified: '2022-06-08T12:48:41.213537+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7747
  title: བོད་ཀྱི་དག་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    8C45:
      image_group_id: I3CN8712
      title: ''
      total_pages: 292
      order: 1
      base_file: 8C45.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
